### ISSUE TITLE
Minimal steps for running example

### ISSUE THREAD

**Issue by bjornborg** [jampekka/webtrajsim#23]
Hi,
I am studying the paper "Humans Use Predictive Gaze Strategies to Target Waypoints for Steering" which refers to this repository.

I've been trying to configuring and building in order to get a running example as in the paper without success (with minimal javascript and npm knowledge, npm installation of dependencies seems to be broken I think). Are there any tutorials or steps to get this up and running?

**Comment by jampekka** [comment]
Sorry, i just noticed this from the closing notification. @samtuhka was the main developer for that article's setup and would probably know better how to set it up.
